### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by winfried-van-loon** [joelcarlton/Sublime-CombineAndMinify#3]
Hi, I keep getting the following error at startup. What can I do to resolve it?

```
reloading plugin CombineAndMinify.CombineAndMinfiy
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "CombineAndMinfiy in C:\Users\Stagiair\AppData\Roaming\Sublime Text 3\Installed Packages\CombineAndMinify.sublime-package", line 27
    print '\nInitiating Minification'
                                    ^
SyntaxError: invalid syntax
```

Thank you.

**Comment by joelcarlton** [comment]
Looking into it. Sorry for delay.

**Comment by joelcarlton** [comment]
This is an issue with ST3 as the package was not compatible. ST3 version coming soon.
